# FILE/DIRECTORY INFORMATION
FILE_PATH = r'C:\repos\PDF_Downloader\_files\GRI_2017_2020 (1).xlsx'
OUTPUT_PATH = r'C:\repos\PDF_Downloader\output_dir'
OUTPUT_FILE_SUCCESS = "report_Success.txt"
OUTPUT_FILE_FAIL = "report_Failure.txt"

# SPREADSHEET INFORMATION
ID_COL_NAME = 'BRnum'
URL_COL_NAME = 'Pdf_URL'
URL_BACKUP_COL_NAME = 'Report Html Address'

# REMOVES FILES WITHIN OUTPUT_DIR
CLEAN_OUTPUT = False

# TESTING VARIABLES
CAP_TOTAL_AMOUNT_OF_ROWS = 1
NUMBER_OF_THREADS = 10
TIMEOUT_REQUEST_MAX = 0.25
DOWNLOAD_FILES = True
SKIP_IF_IN_RESULT_REPORT = True
IN_PROGRESS = True